// Supabase configuration
export const supabaseUrl = "https://lczeeincuqzfczdcrlvd.supabase.co";
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjemVlaW5jdXF6ZmN6ZGNybHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjUwNTcsImV4cCI6MjA3MDU0MTA1N30.jR56NObu2KpCNlQm29UciPhtjRNt2VZbc0iCAPan_OI";
